Updates from prelive
salemove/android-sdk-widgets pull request #172
Opened 2022-01-10 10:43 UTC by deniss-mc

2022-01-11 09:08 UTC, jakob-mc requested changes

2022-01-11 09:08 UTC, jakob-mc commented on widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorInfo.java
>  }
missing newline

2022-01-11 09:09 UTC, deniss-mc commented on widgetssdk/src/main/java/com/glia/widgets/core/visitor/GliaVisitorInfo.java
>  }
```suggestion
}

```

2022-01-12 14:53 UTC, jakob-mc approved these changes

2022-01-12 14:54 UTC, merged