ChatBubble Improvements
salemove/android-sdk-widgets pull request #190
Opened 2022-02-11 11:09 UTC by deniss-mc

Application ChatBubble Layout Update
Service ChatBubble Update

**Jira issue:**
https://glia.atlassian.net/browse/MUIC-369

**Additional info:**
Resolves also:
https://glia.atlassian.net/browse/MUIC-472
https://glia.atlassian.net/browse/MUIC-313
https://glia.atlassian.net/browse/MUIC-360
https://glia.atlassian.net/browse/MUIC-485
https://glia.atlassian.net/browse/MUIC-483
https://glia.atlassian.net/browse/MUIC-458
https://glia.atlassian.net/browse/MUIC-487
https://glia.atlassian.net/browse/MUIC-482
https://glia.atlassian.net/browse/MUIC-542
https://glia.atlassian.net/browse/MUIC-543

**Known issues**
https://glia.atlassian.net/browse/MUIC-659
https://glia.atlassian.net/browse/MUIC-660 (related to 659)

**Screenshots:**
<img width="386" alt="SC1" src="https://user-images.githubusercontent.com/49229744/153581087-60e27231-cebb-4fd4-b804-9f5a6a8f540c.png">
<img width="386" alt="SC2" src="https://user-images.githubusercontent.com/49229744/153581262-3353f40b-d1f4-4bc6-b923-881f7e4a0806.png">

2022-02-14 15:41 UTC, AndriiHorishniiMOC commented on widgetssdk/src/main/java/com/glia/widgets/chat/ChatView.java
> +    public void onDestroyView(boolean isFinishing) {
There should be a description of the `isFinishing` parameter.

2022-02-15 16:41 UTC, jakob-mc requested changes

2022-02-15 16:41 UTC, jakob-mc commented on widgetssdk/src/main/java/com/glia/widgets/core/chathead/domain/ResolveChatBubbleNavigationUseCase.java
> +        } else if (isChatEngagementOngoing() || isChatQueueingOngoing()) {
this if-else looks unnecessary because final else returns the same

2022-02-15 16:41 UTC, jakob-mc commented on widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
> +    private static final LifecycleEventObserver lifecycleEventObserver = (source, event) -> {
does it have to be static and global?

2022-02-15 16:41 UTC, jakob-mc commented on widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadLayout.java
> +        float floatingViewX = w - getResources().getDimension(R.dimen.glia_chat_head_size)
pls break it down to multiple statements

2022-02-15 16:41 UTC, jakob-mc commented on widgetssdk/src/main/java/com/glia/widgets/view/head/controller/ServiceChatBubbleController.java
> +    private final UnsubscribeFromQueueingStateChangeUseCase unsubscribeFromQueueingStateChangeUseCase;
not used

2022-03-08 08:03 UTC, jakob-mc requested changes

2022-03-08 08:03 UTC, jakob-mc commented on widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
> +        lifecycleManager.addObserver((source, event) -> {
separate method pls if possible.

2022-03-08 08:03 UTC, jakob-mc commented on widgetssdk/src/main/java/com/glia/widgets/view/head/ChatHeadLayout.java
> +    public void setIsChatView(boolean value) {
pls follow the correct order of methods: overridden, public, private

2022-03-10 09:09 UTC, jakob-mc approved these changes

2022-03-10 09:09 UTC, jakob-mc commented on widgetssdk/src/main/java/com/glia/widgets/di/Dependencies.java
> +                controllerFactory.getChatHeadController()
those arguments can be moved to the `initApplicationLifecycleObserver()`

2022-03-10 14:46 UTC, AndriiHorishniiMOC approved these changes

2022-03-10 14:56 UTC, merged