Devs want to show/hide attachment button depends on site configuration
salemove/android-sdk-widgets pull request #228
Opened 2022-03-23 09:11 UTC by DavDo

**Jira issue:**
https://glia.atlassian.net/browse/MOB-1191?atlOrigin=eyJpIjoiOTZlOTE1YjFmMjAxNDhiOThiMDY0NmZhZTI2MDc2OGEiLCJwIjoiaiJ9

MOB-1191

2022-03-23 13:28 UTC, gugalo approved these changes

2022-03-23 20:15 UTC, AndriiHorishniiMOC approved these changes

2022-03-24 07:59 UTC, deniss-mc requested changes
Change target branch to develop (rebase)

2022-03-25 11:16 UTC, deniss-mc commented
This will need to be combined with the Configuration approach at some point @jakob-mc 

At the moment Looks OK

@dukhovnyi  what should happen if information query will fail? does it need to retry? should it default to some parameters?

2022-03-25 11:17 UTC, deniss-mc approved these changes

2022-03-25 11:49 UTC, dukhovnyi commented
> This will need to be combined with the Configuration approach at some point CC: @jakob-mc
> 
> At the moment Looks OK
> 
> @dukhovnyi what should happen if information query will fail? does it need to retry? should it default to some parameters?
> 
> We would like to move configuration initialization out of Activity classes at some point - this way we will know if we can put callback to application level or still need to query those each time we enter the Glia Activities

@deniss-mc , in case of failed request we need to show the button and give the possibility to visitors to try to upload files. In case it is unavailable, visitors get the error message as it works now. Does it make sense?
cc: @DavDo

2022-03-25 11:52 UTC, deniss-mc commented on widgetssdk/src/main/java/com/glia/widgets/chat/controller/ChatController.java
> +                .setIsAttachmentButtonNeeded(false)
id still call it visible :)

2022-03-25 13:08 UTC, deniss-mc commented
> > This will need to be combined with the Configuration approach at some point CC: @jakob-mc
> > At the moment Looks OK
> > @dukhovnyi what should happen if information query will fail? does it need to retry? should it default to some parameters?
> > We would like to move configuration initialization out of Activity classes at some point - this way we will know if we can put callback to application level or still need to query those each time we enter the Glia Activities
> 
> @deniss-mc , in case of failed request we need to show the button and give the possibility to visitors to try to upload files. In case it is unavailable, visitors get the error message as it works now. Does it make sense? cc: @DavDo

I ment if the SiteInfo request from hub fails (there could be more configuration options like white label thingy, call disable etc. endless possibilities :) ). In case of attachments it should default to 'show' then - at the moment I see

`siteInfo == null` = don't show

2022-03-25 14:04 UTC, DavDo commented
> > This will need to be combined with the Configuration approach at some point CC: @jakob-mc
> > At the moment Looks OK
> > @dukhovnyi what should happen if information query will fail? does it need to retry? should it default to some parameters?
> > We would like to move configuration initialization out of Activity classes at some point - this way we will know if we can put callback to application level or still need to query those each time we enter the Glia Activities
> 
> @deniss-mc , in case of failed request we need to show the button and give the possibility to visitors to try to upload files. In case it is unavailable, visitors get the error message as it works now. Does it make sense? cc: @DavDo

@dukhovnyi In case of request with **App Token** we always receive null for SiteInfo that for I think we need to hide button only when `isVisitorAllowed() == false`

2022-03-25 14:28 UTC, deniss-mc approved these changes

2022-03-25 14:30 UTC, merged