Fixed end screen sharing dialog anomalies
salemove/android-sdk-widgets pull request #542
Opened 2023-04-10 07:04 UTC by Pelkar

MOB-2007

The problematic flow was the following:

- Set engagement to not have a survey
- Start chat engagement with operator connected
- minimize the chat screen
- disconnect the operator
- click on bubble

Expected result:
- engagement ended dialog is shown

Actual result:
- app would show unexpected dialog
- when starting a new chat engagement, the engegement ended dialog is shown

2023-04-10 09:41 UTC, DavDo approved these changes

2023-04-10 10:11 UTC, gugalo approved these changes

2023-04-10 18:33 UTC, andrews-moc requested changes
As we discussed with Karl in Slack, we need to implement the same fix for `CallController` as well.

Test case:
- Start Call Visualizer engagement
- Request 1-way video as an operator, accept it as visitor
- End call by operator
- Start new Call Visualizer engagement
- Request 1-way video as an operator

Expected result: incoming media upgrade request is displayed, visitor can accept it and is navigated to Call screen
Actual result: no incoming media upgrade request, Call screen is not opened.

This is because instead of `MODE_MEDIA_UPGRADE`, `MODE_ENGAGEMENT_ENDED` is received.

2023-04-10 18:36 UTC, andrews-moc commented
I would suggest adding comments to each `shouldHandleEndedEngagement` variable value change to explain the reason behind the change. It will help us a lot if we need to adjust something in this logic in the future, I think.

2023-04-12 13:12 UTC, andrews-moc commented on widgetssdk/src/main/java/com/glia/widgets/core/chathead/CurrentEngagementStateManager.kt
> +}
And if so, then `CurrentEngagementStateManager` is actually a `SurveyStateManager`. 🤔

2023-04-13 05:15 UTC, Pelkar commented on widgetssdk/src/main/java/com/glia/widgets/core/chathead/CurrentEngagementStateManager.kt
> +}
I made this enum as a proof of concept for the suggestion of recording engagement steps and handling changes in one place. For now I just removed all other steps to not have unused code.

2023-04-13 08:07 UTC, andrews-moc commented on widgetssdk/src/main/java/com/glia/widgets/core/chathead/CurrentEngagementStateManager.kt
> +}
Discussed this on a call, @Pelkar will do some renaming.
It will not affect the logic, so I'm approving the PR.

2023-04-13 12:06 UTC, merged