Fix Speaker mode gets stuck in the ON state
salemove/android-sdk-widgets pull request #619
Opened 2023-05-25 20:05 UTC by AndriiHorishniiMOC

`AudioManager` from the application context works without stuck.

Also, the `setSpeakerphoneOn()` does not apply instantly. `BehaviorSubject` with `distinctUntilChanged()` is used to prevent multiple identical values from being applied.

[MOB-2234](https://glia.atlassian.net/browse/MOB-2234)

2023-05-29 03:39 UTC, Pelkar approved these changes
Good find indeed!

2023-05-29 08:35 UTC, DavDo approved these changes

2023-05-29 12:00 UTC, gugalo requested changes
Please add a comment in the code so that no one 'optimizes' this line in the future. Can also just add a bug ticket link with short explanation

2023-05-30 06:09 UTC, DavDo commented
> 1965600

fixed - [1965600](https://github.com/salemove/android-sdk-widgets/pull/619/commits/1965600e08a6b4be84f330d275d6490f3c02aba0)

2023-05-30 06:29 UTC, gugalo approved these changes

2023-05-30 06:30 UTC, gugalo commented
!squash

2023-05-30 07:06 UTC, merged