Improve transitions btw Screens
salemove/android-sdk-widgets pull request #896
Opened 2024-01-19 15:40 UTC by DavDo

MOB 3002

**Jira issue:**
https://glia.atlassian.net/browse/MOB-xxx

**What was solved?**

**Release notes:**

 - [ ] Feature
 - [x] Ignore
 - [ ] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

**Additional info:**

 - [ ] Tests updated? Added? Unit, acceptance, snapshots?
 - [ ] Logging for future troubleshooting of client issues added?

**Screenshots:**

2024-01-22 05:30 UTC, Pelkar commented
FYI: You forgot to change the link to issue in the description

2024-01-22 05:34 UTC, Pelkar requested changes
A few things that need attention

2024-01-22 05:34 UTC, Pelkar commented on widgetssdk/src/main/java/com/glia/widgets/base/BasFadeActivity.kt
> +open class BasFadeActivity : AppCompatActivity() {
BaseFadeActivity?

2024-01-22 05:34 UTC, Pelkar commented on widgetssdk/src/main/res/values/colors.xml
> +    <color name="glia_transparent_black_bg">#232323</color>
No transparency any more?

Should we maybe change the resource name as well or create a new one to avoid confusion?

2024-01-22 07:41 UTC, DavDo commented on widgetssdk/src/main/java/com/glia/widgets/base/BasFadeActivity.kt
> +open class BasFadeActivity : AppCompatActivity() {
BaseFadeTransitionActivity?

2024-01-22 14:15 UTC, andrews-moc commented on widgetssdk/src/main/java/com/glia/widgets/base/BasFadeActivity.kt
> +        super.onCreate(savedInstanceState)
I think `super` calls should be on the first line of the function everywhere in this class.

2024-01-23 08:06 UTC, AndriiHorishniiMOC approved these changes
Snapshot tests feel the changes :)

2024-01-23 11:48 UTC, gugalo approved these changes

2024-01-23 13:15 UTC, merged