Made testing build with release settings
salemove/android-sdk-widgets pull request #939
Opened 2024-02-07 19:25 UTC by AndriiHorishniiMOC

**Jira issue:**
https://glia.atlassian.net/browse/MOB-2444

**What was solved?**

- Added ability to make local maven release.
- Set "minifyEnabled true" for the test application build that is used for the acceptance testing.
- Set "release" as a build variant for the testing app build task.

**Release notes:**

 - [ ] Feature
 - [x] Ignore
 - [ ] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

**Additional info:**

 - [ ] Tests updated? Added? Unit, acceptance, snapshots?
 - [ ] Logging for future troubleshooting of client issues added?

**Screenshots:**

2024-02-08 11:06 UTC, DavDo approved these changes
LGTM

2024-02-08 12:52 UTC, andrews-moc approved these changes

2024-02-09 10:02 UTC, gugalo approved these changes

2024-02-09 10:02 UTC, gugalo commented on bitrise.yml
> +    INTEGRATOR_VARIANT: release
Why not just 'RELEASE_VARIANT'?

2024-02-09 10:30 UTC, gugalo requested changes
Could we discuss this on stendup on Monday

2024-02-12 21:05 UTC, DavDo commented on build.gradle
>      maven { url "https://s01.oss.sonatype.org/content/repositories/comglia-1253" }
Could you please remove this since you have touched this file)

2024-02-12 21:06 UTC, DavDo approved these changes
LGTM

2024-02-13 07:01 UTC, Pelkar approved these changes
LGTM

2024-02-13 10:24 UTC, andrews-moc approved these changes

2024-02-15 08:20 UTC, AndriiHorishniiMOC commented
!merge

2024-02-15 08:21 UTC, AndriiHorishniiMOC commented
!squash

2024-02-15 08:39 UTC, merged